language: node_js
node_js: — "11.0.0"
before_script: npm install -g ionic
install: npm install
script: ionic build --prod -- --base-href https://seagomezar.github.io/Ionic4-Music-Starter/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: www
